### PR TITLE
Fix Windows GraphViz and paths construction

### PR DESCRIPTION
**Pull request by LukasZahradnik**
Hello,

This PR fixes paths problems on different platforms (Windows), which I discovered thanks to [this issue](https://github.com/LukasZahradnik/PyNeuraLogic/issues/32).

- Removed constructing paths via string concatenating (with `"/"` as separator)
- Removed `':'` from template path sanitizing (Caused paths like `C:\...` to be sanitized as `C_\...`)
- Calling `dot.exe` directly (for some reason, `dot.exe` was supposed to be in `Resources/graphviz`)

This PR is more focused on the Windows platform. There might be more issues related to macOS - it got [stuck on my tests](https://github.com/LukasZahradnik/PyNeuraLogic/actions/runs/2009074714) while trying to use graphviz to draw templates/samples in macOS.

### CODE REVIEW

**Comment by GustikS** [comment]
Hello, thank you! 

> Removed constructing paths via string concatenating (with "/" as separator)
A bit weird, I'm quite sure I tested that windows can handle the "/" separators, but it's long time ago... this is surely better anyway.

> Removed ':' from template path sanitizing (Caused paths like C:\... to be sanitized as C_\...)
hmm, but that's kind of the point of the sanitization, the output template name should not be a valid path, just a filename... plus I only see it used in the rare use-case of multiple templates... where is it used in this case?

> (for some reason, dot.exe was supposed to be in Resources/graphviz)
yeah, that's where I had it :) so now you just assume dot.exe to be on global path in windows?

> There might be more issues related to macOS
yeah, that's very likely, I never tested on a Mac...

**Comment by LukasZahradnik** [comment]
> A bit weird, I'm quite sure I tested that windows can handle the "/" separators, but it's long time ago... this is surely better anyway.

It might have worked as it was. I could do only limited debugging as the only Windows I have access to is in Github Actions. This change was more like a "just to be sure" change.

> hmm, but that's kind of the point of the sanitization, the output template name should not be a valid path, just a filename... plus I only see it used in the rare use-case of multiple templates... where is it used in this case?

It gets called [here](https://github.com/GustikS/NeuraLogic/blob/master/Settings/src/main/java/cz/cvut/fel/ida/setup/SourceFiles.java#L140). I use params to specify template (`-t`), examples (`-e`), and queries (`-q`), so for example
```
-t ./Resources/datasets/relational/molecules/mutagenesis/templates/template.txt
-e ./Resources/datasets/relational/molecules/mutagenesis/examples.txt
-q ./Resources/datasets/relational/molecules/mutagenesis/queries.txt
```
In the case of the python frontend, those paths are absolute paths...

> yeah, that's where I had it :) so now you just assume dot.exe to be on global path in windows?

Yes

**Comment by GustikS** [comment]
> It gets called [here](https://github.com/GustikS/NeuraLogic/blob/master/Settings/src/main/java/cz/cvut/fel/ida/setup/SourceFiles.java#L140). I use params to specify template (-t), examples (-e), and queries (-q), so for example

yes, so that's what I meant. But what's the problem with that? This is only used for a temporary "merged" template file creation in case of multiple templates. This function is then only to get an ad-hoc filename for that temp file, which shouldn't matter at all (as long as it's a valid unique filename), here it will be:

`_Resources_datasets_relational_molecules_mutagenesis_templates_template.txt`

...+ it works OK for me on windows, e.g.:

`java -jar Neuralogic.jar ... -t C:\Users\gusta\Downloads\NeuraLogic-master\Resources\datasets\simple\family\templateX.txt `

>...dot.exe... Yes 

Alright, definitely better than a fixed path, but still, it will rarely be the case with windows users to have dot.exe on Path. Would it be possible to install/add dot to windows Path during the pip install? :)

Thanks

**Comment by LukasZahradnik** [comment]
> yes, so that's what I meant. But what's the problem with that? This is only used for a ...

Maybe I misunderstand something. I'm passing only `-t`, `-q`, and `-e` parameters (without `-sd`), and it was failing on the Mutagenesis dataset. From [the code](https://github.com/GustikS/NeuraLogic/blob/master/Settings/src/main/java/cz/cvut/fel/ida/setup/SourceFiles.java#L358), it looks like the `-t` template can be a normal path. 

> Alright, definitely better than a fixed path, but still, it will rarely be the case with windows ...

I got a report in the issue linked in the previous comment that the rendering is not working on mac either. Maybe it would be best to call `dot` without any path specification - dot has to be on Path on all platforms; if it's not, then users would simply specify the full path to dot, , e.g.:

```py
draw_model(model, ..., graphviz_path="C:\custom\location\dot.exe")
```
And we could also add some global variables/env variables for the Graphviz path. I think that would be better than installing Graphviz and adding it to the path during pip install. Visualization is optional, and it might introduce some other issues.

**Comment by GustikS** [comment]
> ...and it was failing on the Mutagenesis dataset.

ah ok, I see now - there's an "import ./..." in that template. In that case we should sanitize even further the "\" in windows paths... let me fix that.

> draw_model(model, ..., graphviz_path="C:\custom\location\dot.exe")

yeah, that would be great, can you do that? From the feedback, I think that drawing is a vital part of the library for the users. Would be nice to add some check if dot is on the Path if a user attempts drawing, and redirect them where to pip install it if not...

**Pull request closed without merging**
